platform :ios, '8.0'
target'StartDemo'do
    pod 'CTMediator', '~> 12'
    pod 'SDCycleScrollView', '~> 1.73'
    pod 'Masonry', '~> 1.0.2'
    pod 'YYCache', '~> 1.0.4'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'YYModel', '~> 1.0.4'
    pod 'MJExtension', '~> 3.0.13'
end
